#Workflow name
name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  #Build job
  node_pipeline:
    name: Node.js Pipeline
    permissions:
      id-token: write
      pages: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      #Set up Node 18
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      #Node Dependency Installation
      - name: Installing Dependencies
        run: npm install
      #Fix package-lock.json if it is broken
      - name: Fixing package-lock.json
        run: npm install && npm ci
      #Run Node Build
      - name: Run npm build
        run: npm run build
      #Setup Github Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      #Upload files
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: './dist'
      #Deploy to Github Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2